name: Fail if New Spec

on: pull_request

jobs:
  fail-new-spec:
    name: Fail if New Spec

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Check for new specs
      run: |
        set +o pipefail # Disable pipefail
        set +e # Disable exit on error

        CHANGED_SPECS=$(git diff --name-only HEAD^ HEAD | grep ".json$")

        if [[ -z "$CHANGED_SPECS" ]]; then
          echo "No changed specs"
          exit 0
        fi

        EXIT_CODE=0
        for SPEC in $CHANGED_SPECS; do
          echo "SPEC: $SPEC"
          SPEC_DIR=$(dirname $(dirname $(dirname $SPEC)))
          echo "SPEC_DIR: $SPEC_DIR"
          DIR_IN_TARGET_BRANCH=$(git ls-tree HEAD^ $SPEC_DIR)
          if [[ -n "$DIR_IN_TARGET_BRANCH" ]]; then
            echo "$SPEC_DIR exists in target branch, so spec is not new"
          else
            echo "$SPEC_DIR does not exist in target branch, so spec is new"
            EXIT_CODE=1
          fi
          echo
        done
        exit $EXIT_CODE
