name: NewOrIncrementalTypeSpecChange

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]


jobs:
  add-arm-auto-signoff:
    name: NewOrIncrementalTypeSpecChange

    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Add or Remove Label
      uses: actions/github-script@v7
      with:
        script: |
          const determineNewOrIncrementalTypeSpecChange = require('./.github/workflows/scripts/arm-new-incremental-typespec.js')
          await determineNewOrIncrementalTypeSpecChange({ github, context, core });
